version: '3'
services:
  flask:
    build: ./ALWIDA_admin
    image: alwida/admin
    ports:
      - 8888:8888
    volumes:
      - ./ALWIDA_admin:/usr/src/app
    environment:
      - TZ=Asia/Seoul
  mariadb:
    build: ./MariaDB
    image: alwida/mariadb
    volumes:
      - ./MariaDB/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Seoul
    
